### ISSUE TITLE
Thanh Van's Review - Lab 1

### ISSUE THREAD

**Issue by tcvan0707** [kiennguyenchi/potato-generator#1]
- Overall, your code is looking good, all the functions work properly, I try to modify the .txt file to see if any error, but you handle it very well. Nothing changes in format as well as structure.
- For the instruction of how to run your code, you should include the command-line to run your code in "Without specified argument".
- Besides, your code is short and format properly, so it is easier for me to know what is going on in each step.

**Comment by kiennguyenchi** [comment]
Thank you for the feedback! I fixed the issue!
